"""empty message

Revision ID: 40aa3e534988
Revises: 
Create Date: 2020-12-09 20:45:01.354332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40aa3e534988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weightsdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=40), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jardevices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('weight_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['weight_id'], ['weightsdata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jardevices')
    op.drop_table('weightsdata')
    # ### end Alembic commands ###
